MyFirstWebSite/Controllers/IndexController.cs
//using MyFirstWebSite.Authorise;
using MyFirstWebSite.Controllers.DBReadWrite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstWebSite.Controllers
{
    public class IndexController : Controller
    {

        public ActionResult PartCv()
        {
            return View();
        }

        // GET: Index
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomePage()
        {
            return View();
        }

        [Authorize]
        public ActionResult CV()
        {
            return View();
        }

        [Authorize]
        public ActionResult Welcome()
        {
            return View();
        }

    }
}

MyFirstWebSite/Views/Shared/_Footer.cshtml
<div id="footer">
    <ul>
        <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="~/graphics/linkedin.jpg" width="48" height="48"></a></li>
        <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="/graphics/facebook.jpg" width="48" height="48"></a></li>
        <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="/graphics/github.jpg" width="48" height="48"></a></li>
    </ul>
</div>

MyFirstWebSite/Views/Shared/_FullLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="author" content="Brian" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.4.4.min.js" )" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.json-2.2.min.js" type="text/javascript"></script>

    <script src="~/scripts/My_Code.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
        <body style="background-color:darkgrey">          
            <div id="wrap">
                <div id="mainarea">
                    <div id="header">
                        <nav>
                            <ul>
                                <li><a href="https://www.github.com">GitHub</a></li>
                                <li><a href="https://www.facebook.com" target="_blank">Facebook</a></li>
                                <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank">LinkedIn</a></li>
                            </ul>
                        </nav>
                    </div>

                    <div id="sidebar">
                        <nav>
                            <ul>
                                <li>@Html.ActionLink("About Me", "HomePage", "Index")</li>
                                <li><a href="https://www.google.ie">Future Projects For Download</a></li>
                                <li>@Html.ActionLink("CV To Date", "CV", "Index")</li>
                                <li><a href="https://www.google.ie">Ask A Question</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div id="content">
                            @RenderBody()


                    </div>
                    <div id="footer">
                        <ul>
                            <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="~/graphics/linkedin.jpg" width="48" height="48"></a></li>
                            <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="/graphics/facebook.jpg" width="48" height="48"></a></li>
                            <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="/graphics/github.jpg" width="48" height="48"></a></li>
                        </ul>
                    </div><!--Main Area-->
                </div>                        
              </div>
        </body>
</html>

MyFirstWebSite/Views/Shared/_Header.cshtml
<div id="header">
    <nav>
        <ul>
            <li><a href="https://www.github.com">GitHub</a></li>
            <li><a href="https://www.facebook.com" target="_blank">Facebook</a></li>
            <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank">LinkedIn</a></li>
        </ul>
    </nav>
</div>

MyFirstWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MyFirstWebSite/Views/Shared/_MenuOptions.cshtml
@{
    Layout = null;
}


@if(Request.IsAuthenticated)
{

    <strong>@Html.Encode(User.Identity.Name)</strong>
    @Html.ActionLink("Log Out", "Logout", "User", new { @class = "button" })<span>|</span>@Html.ActionLink("Check Previos Logins", "PreviousLogins", "User")
}
else
{
    @Html.ActionLink("Register","Register", "User")
    <span>|</span>@Html.ActionLink("Log In", "Login", "User")
}

MyFirstWebSite/Views/Shared/_ResponsiveLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="author" content="Brian" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.4.4.min.js" )" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.json-2.2.min.js" type="text/javascript"></script>
    <script src="~/scripts/My_Code.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/BootstrapStylesheet.css">
</head>
<body style="background-image:url(../graphics/bg_green.jpg)">
    <div id="wrap">
        <div id="header">
            <nav class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">Brian Joyce</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="#">Github</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Linkedin</a></li>
                    </ul>
                </div>
            </nav>
        </div>
        <div id="mainarea">
            @RenderBody()
        </div>
        <div id="footer">
            <nav class="navbar navbar-default">
                <div class="container">
                    <ul class="nav navbar-nav">
                        <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="http://localhost:53083/graphics/linkedin.jpg" width="48" height="48" class="img-responsive"></a></li>
                        <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="http://localhost:53083/graphics/facebook.jpg" width="48" height="48" class="img-responsive"></a></li>
                        <li><a href="https://www.linkedin.com/in/brianthomasjoyce" target="_blank"><img src="http://localhost:53083/graphics/github.jpg" width="48" height="48" class="img-responsive"></a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</body>
</html>

MyFirstWebSite/Views/Shared/_Scripts.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="width=device-width, initial-scale=1">
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="Brian">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.json-2.2.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="~/scripts/My_Code.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="~/Content/style.css">

MyFirstWebSite/Views/Shared/_Sidebar.cshtml
<div id="sidebar">
    <nav>
        <ul>
            <li>@Html.ActionLink("About Me", "HomePage", "Index")</li>
            <li><a href="https://www.google.ie">Future Projects For Download</a></li>
            <li>@Html.ActionLink("CV To Date", "CV", "Index")</li>
            <li><a href="https://www.google.ie">Ask A Question</a></li>
        </ul>
    </nav>
</div>